// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PmfMdBr1jPFrmatUOxDNF3Jqhzf920Q',
    appId: '1:638377195713:web:9bc8b92da1025bbfe97c40',
    messagingSenderId: '638377195713',
    projectId: 'synccash-d9c04',
    authDomain: 'synccash-d9c04.firebaseapp.com',
    storageBucket: 'synccash-d9c04.firebasestorage.app',
    measurementId: 'G-F8LWPK3SHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrpOPJGhCQr1-FZSozIbYivrWplUMyk8I',
    appId: '1:638377195713:android:cab87866d9e42a82e97c40',
    messagingSenderId: '638377195713',
    projectId: 'synccash-d9c04',
    storageBucket: 'synccash-d9c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFMfDulsoUtGJiyt22la9FFuyJU6stcGw',
    appId: '1:638377195713:ios:6915d0c276496e89e97c40',
    messagingSenderId: '638377195713',
    projectId: 'synccash-d9c04',
    storageBucket: 'synccash-d9c04.firebasestorage.app',
    iosBundleId: 'com.example.synccash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8PmfMdBr1jPFrmatUOxDNF3Jqhzf920Q',
    appId: '1:638377195713:web:3c8b088657e05077e97c40',
    messagingSenderId: '638377195713',
    projectId: 'synccash-d9c04',
    authDomain: 'synccash-d9c04.firebaseapp.com',
    storageBucket: 'synccash-d9c04.firebasestorage.app',
    measurementId: 'G-YC2GLJGQJZ',
  );
}
